<?xml version="1.0" encoding="UTF-8"?>
<project
        xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>tr.org.tspb</groupId>
    <artifactId>fms</artifactId>
    <version>1.6.3-alpha</version>
    <packaging>pom</packaging>
    <name>${project.groupId} : ${project.artifactId} : ${project.version}</name>

    <modules>
        <module>common</module>
        <module>constants</module>
        <module>factory</module>
        <module>notification</module>
        <module>datamodel</module>
        <module>util</module>
        <module>outsider</module>
        <module>converter</module>
        <module>service</module>
        <module>fgtpswd</module>
        <module>workflow</module>
        <module>pivot</module>
        <module>logger</module>
        <module>table</module>
        <module>page</module>
        <module>fms-ejb</module>
        <module>fms-war</module>
        <module>fms-ear</module>
    </modules>

    <repositories>

        <!--        
        https://backstage.forgerock.com/knowledge/kb/article/a15127846
        
        Maven 3.8.1 removes support for accessing Maven repositories over HTTP for security reasons. 
        See Maven Release Notes - CVE-2021-26291 for further information.
        https://maven.apache.org/docs/3.8.1/release-notes.html#cve-2021-26291
        -->

        <repository>
            <id>KamuSM</id>
            <url>https://nexus.ozguryazilim.com.tr/content/repositories/KamuSM</url>
        </repository>
        <repository>
            <id>prime-repo</id>
            <name>PrimeFaces Maven Repository</name>
            <url>https://repository.primefaces.org</url>
            <layout>default</layout>
        </repository>

        <repository>
            <id>jasperreports</id>
            <url>https://jasperreports.sourceforge.net/maven2</url>
        </repository>

    </repositories>

    <properties>
        <jdk.source>17</jdk.source>
        <jdk.target>17</jdk.target>
        <jdk.debug>true</jdk.debug>
        <jdk.optimize>false</jdk.optimize>
        <encoding>UTF-8</encoding>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.release>17</maven.compiler.release>

        <fms.version>${project.version}</fms.version>
        <fms.common.version>${project.version}</fms.common.version>
        <fms.constants.version>${project.version}</fms.constants.version>
        <fms.converter.version>${project.version}</fms.converter.version>
        <fms.datamodel.version>${project.version}</fms.datamodel.version>
        <fms.factory.version>${project.version}</fms.factory.version>
        <fms.fgtpswd.version>${project.version}</fms.fgtpswd.version>
        <fms.logger.version>${project.version}</fms.logger.version>
        <fms.notification.version>${project.version}</fms.notification.version>
        <fms.outsider.version>${project.version}</fms.outsider.version>
        <fms.page.version>${project.version}</fms.page.version>
        <fms.pivot.version>${project.version}</fms.pivot.version>
        <fms.service.version>${project.version}</fms.service.version>
        <fms.table.version>${project.version}</fms.table.version>
        <fms.util.version>${project.version}</fms.util.version>

        <fms.esign.version>1.6.0</fms.esign.version>

        <fms.printer.version>1.0.0</fms.printer.version>
        <fms.webclient.version>1.0.0</fms.webclient.version>
        <fms.workflow.version>1.0.0</fms.workflow.version>

        <slf4j.version>2.0.17</slf4j.version>
        <jakartaee>11.0.0</jakartaee>

        <!--<dependency.scope>provided</dependency.scope>-->
        <dependency.scope>compile</dependency.scope>

        <esign.backend.artifact>fms-esign-core-oyas-backend</esign.backend.artifact>
        <esign.ui.artifact>fms-esign-core-oyas-ui</esign.ui.artifact>

    </properties>


    <dependencyManagement>
        <dependencies>
            <!-- provided -->
            <dependency>
                <groupId>jakarta.platform</groupId>
                <artifactId>jakarta.jakartaee-api</artifactId>
                <version>${jakartaee}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>4.1.0-M1</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.mongodb</groupId>
                <artifactId>mongodb-driver-sync</artifactId>
                <version>5.6.2</version>
            </dependency>
            <dependency>
                <groupId>org.primefaces</groupId>
                <artifactId>primefaces</artifactId>
                <version>16.0.0-RC2</version>
                <!--<version>15.0.14</version>-->
                <!--<version>11.0.0</version>-->
                <!--<classifier>jakarta</classifier>-->
                <type>jar</type>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.webjars.npm</groupId>
                <artifactId>primeflex</artifactId>
                <version>3.3.1</version>
                <!--<version>4.0.0</version>-->
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>org.primefaces</groupId>
                <artifactId>primefaces-themes</artifactId>
                <version>16.0.0-RC2</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.graalvm.js</groupId>
                <artifactId>js-scriptengine</artifactId>
                <version>24.1.2</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>org.graalvm.js</groupId>
                <artifactId>js-language</artifactId>
                <version>24.1.2</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>org.graalvm.polyglot</groupId>
                <artifactId>polyglot</artifactId>
                <version>24.1.2</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>org.graalvm.truffle</groupId>
                <artifactId>truffle-api</artifactId>
                <version>24.1.2</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <!--apache-->
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>5.5.1</version>
                <type>jar</type>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.xmlgraphics</groupId>
                <artifactId>fop</artifactId>
                <version>2.11</version>
                <type>jar</type>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-core</artifactId>
                <version>2.25.4</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>4.5.0</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>2.13.2</version>
                <type>jar</type>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>commons-codec</groupId>
                <artifactId>commons-codec</artifactId>
                <version>1.21.0</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>2.21.0</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-jdk14</artifactId>
                <version>${slf4j.version}</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>dk.brics.automaton</groupId>
                <artifactId>automaton</artifactId>
                <version>1.11-8</version>
                <type>jar</type>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>net.sourceforge.jeval</groupId>
                <artifactId>jeval</artifactId>
                <version>0.9.4</version>
                <type>jar</type>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>com.github.oxo42</groupId>
                <artifactId>stateless4j</artifactId>
                <version>2.5.0</version>
                <type>jar</type>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>1.2.3</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>org.everit.json</groupId>
                <artifactId>org.everit.json.schema</artifactId>
                <version>1.3.0</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.17.0</version>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>19.0</version>
                <type>jar</type>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>com.github.xmlet</groupId>
                <artifactId>htmlApiFaster</artifactId>
                <version>1.0.17</version>
                <exclusions>
                    <exclusion>
                        <groupId>javax.validation</groupId>
                        <artifactId>validation-api</artifactId>
                    </exclusion>
                </exclusions>
                <scope>${dependency.scope}</scope>
            </dependency>
            <dependency>
                <groupId>com.github.xmlet</groupId>
                <artifactId>htmlflow</artifactId>
                <version>4.6</version>
                <type>jar</type>
                <scope>${dependency.scope}</scope>
            </dependency>

            <!--fms jars-->
            <!--
           <dependency>
               <groupId>${project.groupId}</groupId>
               <artifactId>webclient</artifactId>
               <version>${fms.webclient.version}</version>
           </dependency>           
            -->
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>printer</artifactId>
                <version>${fms.printer.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-fgtpswd</artifactId>
                <version>${fms.fgtpswd.version}</version>
                <type>jar</type>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-constants</artifactId>
                <version>${fms.constants.version}</version>
                <type>jar</type>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-common</artifactId>
                <version>${fms.common.version}</version>
                <type>jar</type>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-outsider</artifactId>
                <version>${fms.outsider.version}</version>
                <type>jar</type>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-service</artifactId>
                <version>${fms.service.version}</version>
                <type>jar</type>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-pivot</artifactId>
                <version>${fms.pivot.version}</version>
                <type>jar</type>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-page</artifactId>
                <version>${fms.page.version}</version>
                <type>jar</type>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-table</artifactId>
                <version>${fms.table.version}</version>
                <type>jar</type>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-logger</artifactId>
                <version>${fms.logger.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-workflow</artifactId>
                <version>${fms.workflow.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-datamodel</artifactId>
                <version>${fms.datamodel.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-notification</artifactId>
                <version>${fms.notification.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-util</artifactId>
                <version>${fms.util.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-converter</artifactId>
                <version>${fms.converter.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>fms-factory</artifactId>
                <version>${fms.factory.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>${esign.backend.artifact}</artifactId>
                <version>${fms.esign.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.mongodb</groupId>
                        <artifactId>mongo-java-driver</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>${esign.ui.artifact}</artifactId>
                <version>${fms.esign.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.15.0</version>
                    <configuration>
                        <source>${jdk.source}</source>
                        <target>${jdk.target}</target>
                        <encoding>${encoding}</encoding>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-war-plugin</artifactId>
                    <version>3.5.1</version>
                    <configuration>
                        <failOnMissingWebXml>false</failOnMissingWebXml>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-ejb-plugin</artifactId>
                    <version>3.3.0</version>
                    <configuration>
                        <ejbVersion>4.0</ejbVersion>
                        <generateClient>false</generateClient>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>io.github.git-commit-id</groupId>
                    <artifactId>git-commit-id-maven-plugin</artifactId>
                    <version>9.0.2</version>
                    <configuration>
                        <generateGitPropertiesFile>true</generateGitPropertiesFile>
                        <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties
                        </generateGitPropertiesFilename>
                        <includeOnlyProperties>
                            <includeOnlyProperty>^git.build.(time|version)$</includeOnlyProperty>
                            <includeOnlyProperty>^git.commit.id.(abbrev|full)$</includeOnlyProperty>
                            <includeOnlyProperty>^git.branch$</includeOnlyProperty>
                            <includeOnlyProperty>^git.commit.message.(full|short)$</includeOnlyProperty>
                            <includeOnlyProperty>^git.commit.time$</includeOnlyProperty>
                            <includeOnlyProperty>^git.commit.user.name$</includeOnlyProperty>
                        </includeOnlyProperties>
                        <commitIdGenerationMode>full</commitIdGenerationMode>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>


        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ear-plugin</artifactId>
                <version>3.4.0</version>
                <configuration>
                    <version>10</version>
                    <defaultLibBundleDir>lib</defaultLibBundleDir>
                    <!--<skinnyWars>true</skinnyWars>-->
                    <!--<outputFileNameMapping>@{artifactId}@-@{version}@@{dashClassifier? }@.@{extension}@</outputFileNameMapping>-->
                    <outputFileNameMapping>@{artifactId}@-@{version}@.@{extension}@</outputFileNameMapping>
                    <modules>
                        <webModule>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>fms-web</artifactId>
                            <contextRoot>/</contextRoot>
                        </webModule>
                    </modules>
                    <unpackTypes>war,ejb</unpackTypes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>4.0.0-M2</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>3.3.0</version>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <!-- attached to Maven test phase -->
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>jdepend-maven-plugin</artifactId>
                <version>2.0</version>
            </plugin>
        </plugins>
    </reporting>

    <profiles>
        <profile>
            <id>esignOyas</id>
            <properties>
                <esign.backend.artifact>fms-esign-core-oyas-backend</esign.backend.artifact>
                <esign.ui.artifact>fms-esign-core-oyas-ui</esign.ui.artifact>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>${project.groupId}</groupId>
                    <artifactId>${esign.ui.artifact}</artifactId>
                </dependency>
            </dependencies>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-ear-plugin</artifactId>
                            <version>3.4.0</version>
                            <configuration>
                                <version>10</version>
                                <defaultLibBundleDir>lib</defaultLibBundleDir>
                                <!--<skinnyWars>true</skinnyWars>-->
                                <!--<outputFileNameMapping>@{artifactId}@-@{version}@@{dashClassifier? }@.@{extension}@</outputFileNameMapping>-->
                                <outputFileNameMapping>@{artifactId}@-@{version}@.@{extension}@</outputFileNameMapping>
                                <modules>
                                    <webModule>
                                        <groupId>${project.groupId}</groupId>
                                        <artifactId>fms-web</artifactId>
                                        <contextRoot>/</contextRoot>
                                    </webModule>
                                    <jarModule>
                                        <groupId>tr.org.tspb</groupId>
                                        <artifactId>${esign.ui.artifact}</artifactId>
                                        <bundleDir>/</bundleDir>
                                        <excluded>true</excluded>
                                    </jarModule>
                                </modules>
                                <unpackTypes>war,ejb</unpackTypes>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
        <profile>
            <id>esignKamusm</id>
            <properties>
                <esign.backend.artifact>fms-esign-core-kamusm-backend</esign.backend.artifact>
                <esign.ui.artifact>fms-esign-core-kamusm-ui</esign.ui.artifact>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>${project.groupId}</groupId>
                    <artifactId>${esign.ui.artifact}</artifactId>
                </dependency>
            </dependencies>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-ear-plugin</artifactId>
                            <version>3.4.0</version>
                            <configuration>
                                <version>10</version>
                                <defaultLibBundleDir>lib</defaultLibBundleDir>
                                <!--<skinnyWars>true</skinnyWars>-->
                                <!--<outputFileNameMapping>@{artifactId}@-@{version}@@{dashClassifier? }@.@{extension}@</outputFileNameMapping>-->
                                <outputFileNameMapping>@{artifactId}@-@{version}@.@{extension}@</outputFileNameMapping>
                                <modules>
                                    <webModule>
                                        <groupId>${project.groupId}</groupId>
                                        <artifactId>fms-web</artifactId>
                                        <contextRoot>/</contextRoot>
                                    </webModule>
                                    <jarModule>
                                        <groupId>tr.org.tspb</groupId>
                                        <artifactId>${esign.ui.artifact}</artifactId>
                                        <bundleDir>/</bundleDir>
                                        <excluded>true</excluded>
                                    </jarModule>
                                </modules>
                                <unpackTypes>war,ejb</unpackTypes>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
    </profiles>

</project>

