package tr.org.tspb.service.lms;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.bson.Document;

import tr.org.tspb.service.CommonSrv;
import tr.org.tspb.service.LmsLedgerService;
import tr.org.tspb.util.stereotype.MyServices;

/**
 * POS Offline Sync and Conflict-Resolution Protocol Service.
 * Merges and reconciles offline transaction queues generated by POS hardware during cloud connectivity drops.
 */
@MyServices
@ApplicationScoped
public class LmsSyncService extends CommonSrv {

    private static final long serialVersionUID = 1L;

    @Inject
    private LmsLedgerService ledgerService;

    /**
     * Reconciles a batch of offline POS transactions upon network reconnection.
     */
    public Document reconcileOfflineBatch(String storeId, List<Document> offlineTransactions) {
        if (offlineTransactions == null || offlineTransactions.isEmpty()) {
            return new Document("status", "SUCCESS")
                    .append("processedCount", 0)
                    .append("message", "No offline transactions to process");
        }

        int processed = 0;
        int failed = 0;
        List<String> processedTxIds = new ArrayList<>();
        List<Document> errors = new ArrayList<>();

        for (Document tx : offlineTransactions) {
            String memberCode = tx.getString("memberCode");
            String txType = tx.getString("type");
            Double amount = tx.getDouble("amount");
            Double points = tx.getDouble("points");
            String orderRef = tx.getString("orderRef");
            String offlineTxId = tx.getString("offlineTxId");

            try {
                if ("EARN".equalsIgnoreCase(txType) || "OFFLINE_EARN".equalsIgnoreCase(txType)) {
                    double spendAmount = amount != null ? amount : 0.0;
                    ledgerService.accruePoints(memberCode, spendAmount, orderRef, "LMS_DEFAULT", "GENERAL", offlineTxId);
                    processed++;
                    processedTxIds.add(offlineTxId);
                } else if ("BURN".equalsIgnoreCase(txType) || "OFFLINE_BURN".equalsIgnoreCase(txType)) {
                    double burnPoints = points != null ? points : 0.0;
                    ledgerService.redeemPoints(memberCode, burnPoints, orderRef, offlineTxId);
                    processed++;
                    processedTxIds.add(offlineTxId);
                } else {
                    failed++;
                    errors.add(new Document("offlineTxId", offlineTxId).append("error", "Unsupported offline transaction type: " + txType));
                }
            } catch (Exception e) {
                logger.error("LMS Offline Sync Error for Tx [{}] (Member: [{}])", offlineTxId, memberCode, e);
                failed++;
                errors.add(new Document("offlineTxId", offlineTxId).append("error", e.getMessage()));
            }
        }

        logger.info("LMS POS Offline Sync Complete for Store [{}]: Processed [{}] Failed [{}]", storeId, processed, failed);

        return new Document("status", failed == 0 ? "SUCCESS" : "PARTIAL_SUCCESS")
                .append("storeId", storeId)
                .append("processedCount", processed)
                .append("failedCount", failed)
                .append("processedTxIds", processedTxIds)
                .append("errors", errors)
                .append("syncedDate", new Date());
    }
}
